### ISSUE TITLE
Possible to control two Boinc instances independent from each other?

### ISSUE THREAD

**Issue by hassos246** [SpuelMett/Boinc-Home-Assistant-Integration#1]
Is it possible to control two Boinc instances independent from each other? Or will the integration always start or stop both?

**Comment by SpuelMett** [comment]
It looks like it is possible to connect to multiple instances already, but it will control all at the same time, because it cant distinguish between them. But i will take a lock at it in detail and test this in a few days when i have some time. If it is not possible i will try to implement this. Sounds like a godd idea :)

**Comment by hassos246** [comment]
Yes, it would be really helpful.

**Comment by SpuelMett** [comment]
Took a bit longer to work on this :)
I implemented this feature in a feature branch. It is now possbile do add a second client that can be differentiated with a name. I was not able to test the new feature with two different instances of boinc yet. Furthermore i dont know what exactly happens if someone uses the same name. 

If you want to you could already try it out  :)
I hope i can test it in the next days.
When upgrading it is probably better to delete the old config and add it again after upgrading the integration.

**Comment by hassos246** [comment]
Is it possible to add more then two clients?

I can try it out tomorrow.

**Comment by SpuelMett** [comment]
yes. I dont know if there is any limit enforced by home assistant.
